'use strict';

module.exports = function (sequelize, DataTypes) {
  const Model = sequelize.define('Currency', {
    id: {
      type: DataTypes.BIGINT,
      allowNull: false,
      autoIncrement: true,
      primaryKey: true,
    },
    code: {
      type: DataTypes.STRING(5),
      allowNull: false,
      unique: true
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false
    },
    symbol: {
      type: DataTypes.STRING,
      allowNull: true
    }
  }, {
    charset: 'utf8',
    timestamps: false,
    freezeTableName: true,
    hooks: {},
    getterMethods: {},
    setterMethods: {},
  });

  // Class Method
  Model.getEditableKeys = function (){
    return ['code', 'name', 'symbol'];
  };
  Model.initSeed = function (){
    let currencies = [
      {id:1,	code:'USD',	name:'United States Dollars',	symbol:'$'},
      {id:2,	code:'EUR',	name:'Euro',	symbol:'$'},
      {id:3,	code:'GBP',	name:'United Kingdom Pounds',	symbol:'$'},
      {id:4,	code:'CAD',	name:'Canadian Dollars',	symbol:'$'},
      {id:5,	code:'ALL',	name:'Albanian Lek',	symbol:'$'},
      {id:6,	code:'DZD',	name:'Algerian Dinar',	symbol:'$'},
      {id:7,	code:'AOA',	name:'Angolan Kwanza',	symbol:'$'},
      {id:8,	code:'ARS',	name:'Argentine Pesos',	symbol:'$'},
      {id:9,	code:'AMD',	name:'Armenian Dram',	symbol:'$'},
      {id:10,	code:'AWG',	name:'Aruban Florin',	symbol:'$'},
      {id:11,	code:'AUD',	name:'Australian Dollars',	symbol:'$'},
      {id:12,	code:'BBD',	name:'Barbadian Dollar',	symbol:'$'},
      {id:13,	code:'AZN',	name:'Azerbaijani Manat',	symbol:'$'},
      {id:14,	code:'BDT',	name:'Bangladesh Taka',	symbol:'$'},
      {id:15,	code:'BSD',	name:'Bahamian Dollar',	symbol:'$'},
      {id:16,	code:'BHD',	name:'Bahraini Dinar',	symbol:'$'},
      {id:17,	code:'BYR',	name:'Belarusian Ruble',	symbol:'$'},
      {id:18,	code:'BZD',	name:'Belize Dollar',	symbol:'$'},
      {id:19,	code:'BTN',	name:'Bhutanese Ngultrum',	symbol:'$'},
      {id:20,	code:'BAM',	name:'Bosnia and Herzegovina Convertible Mark',	symbol:'$'},
      {id:21,	code:'BRL',	name:'Brazilian Real',	symbol:'$'},
      {id:22,	code:'BOB',	name:'Bolivian Boliviano',	symbol:'$'},
      {id:23,	code:'BWP',	name:'Botswana Pula',	symbol:'$'},
      {id:24,	code:'BND',	name:'Brunei Dollar',	symbol:'$'},
      {id:25,	code:'BGN',	name:'Bulgarian Lev',	symbol:'$'},
      {id:26,	code:'MMK',	name:'Burmese Kyat',	symbol:'$'},
      {id:27,	code:'KHR',	name:'Cambodian Riel',	symbol:'$'},
      {id:28,	code:'KYD',	name:'Cayman Dollars',	symbol:'$'},
      {id:29,	code:'XAF',	name:'Central African CFA Franc',	symbol:'$'},
      {id:30,	code:'CLP',	name:'Chilean Peso',	symbol:'$'},
      {id:31,	code:'CNY',	name:'Chinese Yuan Renminbi',	symbol:'$'},
      {id:32,	code:'COP',	name:'Colombian Peso',	symbol:'$'},
      {id:33,	code:'KMF',	name:'Comorian Franc',	symbol:'$'},
      {id:34,	code:'CRC',	name:'Costa Rican Colones',	symbol:'$'},
      {id:35,	code:'HRK',	name:'Croatian Kuna',	symbol:'$'},
      {id:36,	code:'CZK',	name:'Czech Koruny',	symbol:'$'},
      {id:37,	code:'DKK',	name:'Danish Kroner',	symbol:'$'},
      {id:38,	code:'DOP',	name:'Dominican Peso',	symbol:'$'},
      {id:39,	code:'XCD',	name:'East Caribbean Dollar',	symbol:'$'},
      {id:40,	code:'EGP',	name:'Egyptian Pound',	symbol:'$'},
      {id:41,	code:'ETB',	name:'Ethiopian Birr',	symbol:'$'},
      {id:42,	code:'XPF',	name:'CFP Franc',	symbol:'$'},
      {id:43,	code:'FJD',	name:'Fijian Dollars',	symbol:'$'},
      {id:44,	code:'GMD',	name:'Gambian Dalasi',	symbol:'$'},
      {id:45,	code:'GHS',	name:'Ghanaian Cedi',	symbol:'$'},
      {id:46,	code:'GTQ',	name:'Guatemalan Quetzal',	symbol:'$'},
      {id:47,	code:'GYD',	name:'Guyanese Dollar',	symbol:'$'},
      {id:48,	code:'GEL',	name:'Georgian Lari',	symbol:'$'},
      {id:49,	code:'HTG',	name:'Haitian Gourde',	symbol:'$'},
      {id:50,	code:'HNL',	name:'Honduran Lempira',	symbol:'$'},
      {id:51,	code:'HKD',	name:'Hong Kong Dollars',	symbol:'$'},
      {id:52,	code:'HUF',	name:'Hungarian Forint',	symbol:'$'},
      {id:53,	code:'ISK',	name:'Icelandic Kronur',	symbol:'$'},
      {id:54,	code:'INR',	name:'Indian Rupees',	symbol:'$'},
      {id:55,	code:'IDR',	name:'Indonesian Rupiah',	symbol:'$'},
      {id:56,	code:'ILS',	name:'Israeli New Shekel',	symbol:'$'},
      {id:57,	code:'JMD',	name:'Jamaican Dollars',	symbol:'$'},
      {id:58,	code:'JPY',	name:'Japanese Yen',	symbol:'$'},
      {id:59,	code:'JEP',	name:'Jersey Pound',	symbol:'$'},
      {id:60,	code:'JOD',	name:'Jordanian Dinar',	symbol:'$'},
      {id:61,	code:'KZT',	name:'Kazakhstani Tenge',	symbol:'$'},
      {id:62,	code:'KES',	name:'Kenyan Shilling',	symbol:'$'},
      {id:63,	code:'KWD',	name:'Kuwaiti Dinar',	symbol:'$'},
      {id:64,	code:'KGS',	name:'Kyrgyzstani Som',	symbol:'$'},
      {id:65,	code:'LVL',	name:'Latvian Lati',	symbol:'$'},
      {id:66,	code:'LBP',	name:'Lebanese Pounds',	symbol:'$'},
      {id:67,	code:'LRD',	name:'Liberian Dollar',	symbol:'$'},
      {id:68,	code:'LTL',	name:'Lithuanian Litai',	symbol:'$'},
      {id:69,	code:'MGA',	name:'Malagasy Ariary',	symbol:'$'},
      {id:70,	code:'MKD',	name:'Macedonia Denar',	symbol:'$'},
      {id:71,	code:'MOP',	name:'Macanese Pataca',	symbol:'$'},
      {id:72,	code:'MVR',	name:'Maldivian Rufiyaa',	symbol:'$'},
      {id:73,	code:'MXN',	name:'Mexican Pesos',	symbol:'$'},
      {id:74,	code:'MYR',	name:'Malaysian Ringgits',	symbol:'$'},
      {id:75,	code:'MUR',	name:'Mauritian Rupee',	symbol:'$'},
      {id:76,	code:'MDL',	name:'Moldovan Leu',	symbol:'$'},
      {id:77,	code:'MAD',	name:'Moroccan Dirham',	symbol:'$'},
      {id:78,	code:'MNT',	name:'Mongolian Tugrik',	symbol:'$'},
      {id:79,	code:'MZN',	name:'Mozambican Metical',	symbol:'$'},
      {id:80,	code:'NAD',	name:'Namibian Dollar',	symbol:'$'},
      {id:81,	code:'NPR',	name:'Nepalese Rupee',	symbol:'$'},
      {id:82,	code:'ANG',	name:'Netherlands Antillean Guilder',	symbol:'$'},
      {id:83,	code:'NZD',	name:'New Zealand Dollars',	symbol:'$'},
      {id:84,	code:'NIO',	name:'Nicaraguan Córdoba',	symbol:'$'},
      {id:85,	code:'NGN',	name:'Nigerian Naira',	symbol:'$'},
      {id:86,	code:'NOK',	name:'Norwegian Kroner',	symbol:'$'},
      {id:87,	code:'OMR',	name:'Omani Rial',	symbol:'$'},
      {id:88,	code:'PKR',	name:'Pakistani Rupee',	symbol:'$'},
      {id:89,	code:'PGK',	name:'Papua New Guinean Kina',	symbol:'$'},
      {id:90,	code:'PYG',	name:'Paraguayan Guarani',	symbol:'$'},
      {id:91,	code:'PEN',	name:'Peruvian Nuevo Sol',	symbol:'$'},
      {id:92,	code:'PHP',	name:'Philippine Peso',	symbol:'$'},
      {id:93,	code:'PLN',	name:'Polish Zlotych',	symbol:'$'},
      {id:94,	code:'QAR',	name:'Qatari Rial',	symbol:'$'},
      {id:95,	code:'RON',	name:'Romanian Lei',	symbol:'$'},
      {id:96,	code:'RUB',	name:'Russian Rubles',	symbol:'$'},
      {id:97,	code:'RWF',	name:'Rwandan Franc',	symbol:'$'},
      {id:98,	code:'WST',	name:'Samoan Tala',	symbol:'$'},
      {id:99,	code:'SAR',	name:'Saudi Riyal',	symbol:'$'},
      {id:100,	code:'STD',	name:'Sao Tome And Principe Dobra',	symbol:'$'},
      {id:101,	code:'RSD',	name:'Serbian dinar',	symbol:'$'},
      {id:102,	code:'SCR',	name:'Seychellois Rupee',	symbol:'$'},
      {id:103,	code:'SGD',	name:'Singapore Dollars',	symbol:'$'},
      {id:104,	code:'SYP',	name:'Syrian Pound',	symbol:'$'},
      {id:105,	code:'ZAR',	name:'South African Rand',	symbol:'$'},
      {id:106,	code:'KRW',	name:'South Korean Won',	symbol:'$'},
      {id:107,	code:'LKR',	name:'Sri Lankan Rupees',	symbol:'$'},
      {id:108,	code:'SRD',	name:'Surinamese Dollar',	symbol:'$'},
      {id:109,	code:'SEK',	name:'Swedish Kronor',	symbol:'$'},
      {id:110,	code:'CHF',	name:'Swiss Francs',	symbol:'$'},
      {id:111,	code:'TWD',	name:'Taiwan Dollars',	symbol:'$'},
      {id:112,	code:'THB',	name:'Thai baht',	symbol:'$'},
      {id:113,	code:'TZS',	name:'Tanzanian Shilling',	symbol:'$'},
      {id:114,	code:'TTD',	name:'Trinidad and Tobago Dollars',	symbol:'$'},
      {id:115,	code:'TND',	name:'Tunisian Dinar',	symbol:'$'},
      {id:116,	code:'TRY',	name:'Turkish Lira',	symbol:'$'},
      {id:117,	code:'TMT',	name:'Turkmenistani Manat',	symbol:'$'},
      {id:118,	code:'UGX',	name:'Ugandan Shilling',	symbol:'$'},
      {id:119,	code:'UAH',	name:'Ukrainian Hryvnia',	symbol:'$'},
      {id:120,	code:'AED',	name:'United Arab Emirates Dirham',	symbol:'$'},
      {id:121,	code:'UYU',	name:'Uruguayan Pesos',	symbol:'$'},
      {id:122,	code:'UZS',	name:'Uzbekistan som',	symbol:'$'},
      {id:123,	code:'VUV',	name:'Vanuatu Vatu',	symbol:'$'},
      {id:124,	code:'VEF',	name:'Venezuelan Bolivares',	symbol:'$'},
      {id:125,	code:'VND',	name:'Vietnamese đồng',	symbol:'$'},
      {id:126,	code:'XOF',	name:'West African CFA franc',	symbol:'$'},
      {id:127,	code:'YER',	name:'Yemeni Rial',	symbol:'$'},
      {id:128,	code:'ZMW',	name:'Zambian Kwacha',	symbol:'$'},
    ];

    return Model.bulkCreate(currencies, {returning: true});
  };

// Instance Method
  Model.prototype.toJSON = function () {
    return this.dataValues;
  };

  return Model;
};
