'use strict';

module.exports = function (sequelize, DataTypes) {
  const Model = sequelize.define('Language', {
    id: {
      type: DataTypes.BIGINT,
      allowNull: false,
      autoIncrement: true,
      primaryKey: true
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false
    }
  }, {
    charset: 'utf8',
    timestamps: false,
    freezeTableName: true,
    hooks: {},
    getterMethods: {},
    setterMethods: {},
  });

  // Class Method
  Model.getEditableKeys = function (){
    return ['name'];
  };
  Model.initSeed = function (){
    let languages = [
      {id:1,	name:'Bahasa Indonesia'},
      {id:2,	name:'Bahasa Malaysia'},
      {id:3,	name:'Chinese - Cantonese'},
      {id:4,	name:'Chinese - Mandarin'},
      {id:5,	name:'English'},
      {id:6,	name:'Filipino'},
      {id:7,	name:'French'},
      {id:8,	name:'German'},
      {id:9,	name:'Hindi'},
      {id:10,	name:'Japanese'},
      {id:11,	name:'Thai'},
      {id:12,	name:'Spanish'},
      {id:13,	name:'Abkhazian'},
      {id:14,	name:'Afrikaans'},
      {id:15,	name:'Akan'},
      {id:16,	name:'Albanian'},
      {id:17,	name:'Amharic'},
      {id:18,	name:'Arabic'},
      {id:19,	name:'Armenian'},
      {id:20,	name:'Assamese'},
      {id:21,	name:'Aymara'},
      {id:22,	name:'Azerbaijani'},
      {id:23,	name:'Bashkir'},
      {id:24,	name:'Basque'},
      {id:25,	name:'Belarusian'},
      {id:26,	name:'Bengali'},
      {id:27,	name:'Bhutani'},
      {id:28,	name:'Bosnian'},
      {id:29,	name:'Breton'},
      {id:30,	name:'Bulgarian'},
      {id:31,	name:'Burmese'},
      {id:32,	name:'Byelorussian'},
      {id:33,	name:'Catalan'},
      {id:34,	name:'Cebuano'},
      {id:35,	name:'Cherokee'},
      {id:36,	name:'Chickasaw'},
      {id:37,	name:'Chinese - Fukien'},
      {id:38,	name:'Chinese - Hakka'},
      {id:39,	name:'Chinese - Shanghainese'},
      {id:40,	name:'Chinese - Teochew'},
      {id:41,	name:'Corsican'},
      {id:42,	name:'Croatian'},
      {id:43,	name:'Czech'},
      {id:44,	name:'Danish'},
      {id:45,	name:'Dutch'},
      {id:46,	name:'Esperanto'},
      {id:47,	name:'Estonian'},
      {id:48,	name:'Fiji'},
      {id:49,	name:'Finnish'},
      {id:50,	name:'Frisian'},
      {id:51,	name:'Fulah'},
      {id:52,	name:'Galician'},
      {id:53,	name:'Georgian'},
      {id:54,	name:'Greek'},
      {id:55,	name:'Greenlandic'},
      {id:56,	name:'Gujarati'},
      {id:57,	name:'Hausa'},
      {id:58,	name:'Hebrew'},
      {id:59,	name:'Hungarian'},
      {id:60,	name:'Icelandic'},
      {id:61,	name:'Interlingua'},
      {id:62,	name:'Irish'},
      {id:63,	name:'Italian'},
      {id:64,	name:'Javanese'},
      {id:65,	name:'Kannada'},
      {id:66,	name:'Kashmiri'},
      {id:67,	name:'Kazakh'},
      {id:68,	name:'Khmer'},
      {id:69,	name:'Kinyarwanda'},
      {id:70,	name:'Kirghiz'},
      {id:71,	name:'Kirundi'},
      {id:72,	name:'Korean'},
      {id:73,	name:'Kurdish'},
      {id:74,	name:'Laothian'},
      {id:75,	name:'Latin'},
      {id:76,	name:'Latvian'},
      {id:77,	name:'Lingala'},
      {id:78,	name:'Lithuanian'},
      {id:79,	name:'Macedonian'},
      {id:80,	name:'Malagasy'},
      {id:81,	name:'Malayalam'},
      {id:82,	name:'Maltese'},
      {id:83,	name:'Maori'},
      {id:84,	name:'Marathi'},
      {id:85,	name:'Mongolian'},
      {id:86,	name:'Nepali'},
      {id:87,	name:'Norwegian'},
      {id:88,	name:'Oriya'},
      {id:89,	name:'Oromo'},
      {id:90,	name:'Pashto'},
      {id:91,	name:'Persian'},
      {id:92,	name:'Polish'},
      {id:93,	name:'Portuguese'},
      {id:94,	name:'Punjabi'},
      {id:95,	name:'Quechua'},
      {id:96,	name:'Romanian'},
      {id:97,	name:'Russian'},
      {id:98,	name:'Samoan'},
      {id:99,	name:'Sanskrit'},
      {id:100,	name:'Serbian'},
      {id:101,	name:'Serbo-Croatian'},
      {id:102,	name:'Shona'},
      {id:103,	name:'Sindhi'},
      {id:104,	name:'Sinhalese'},
      {id:105,	name:'Siswati'},
      {id:106,	name:'Slovak'},
      {id:107,	name:'Slovenian'},
      {id:108,	name:'Somali'},
      {id:109,	name:'Sundanese'},
      {id:110,	name:'Swahili'},
      {id:111,	name:'Swedish'},
      {id:112,	name:'Tajik'},
      {id:113,	name:'Tamil'},
      {id:114,	name:'Tatar'},
      {id:115,	name:'Telugu'},
      {id:116,	name:'Tibetan'},
      {id:117,	name:'Tonga'},
      {id:118,	name:'Turkish'},
      {id:119,	name:'Turkmen'},
      {id:120,	name:'Twi'},
      {id:121,	name:'Ukrainian'},
      {id:122,	name:'Urdu'},
      {id:123,	name:'Uzbek'},
      {id:124,	name:'Vietnamese'},
      {id:125,	name:'Welsh'},
      {id:126,	name:'Wolof'},
      {id:127,	name:'Xhosa'},
      {id:128,	name:'Yiddish'},
      {id:129,	name:'Yoruba'},
      {id:130,	name:'Zulu'},
    ];
    return Model.bulkCreate(languages, {returning: true});
  };
  Model.associate = function (models) {
    Model.belongsToMany(models.User, {
      foreignKey: 'languageId',
      through: {model: models.UserLanguage, as: 'userLanguage'},
      as: 'users'
    });
  };

// Instance Method
  Model.prototype.toJSON = function () {
    return this.dataValues;
  };
  return Model;
};
